version: '3'

networks: 
  bridge-project:
    driver: bridge

services: 
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - bridge-project
    volumes:
      - ./database:/var/lib/mysql
  
  flask:
    container_name: flask
    build: .
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - bridge-project
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./city.txt
        target: /app/src/city.txt
    depends_on:
      - mariadb