version: '3'

networks: 
  bridge-project:
    driver: bridge

services: 
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
      MYSQL_DATABASE: weather
    ports:
      - 3306:3306
    tty: true
    networks:
      - bridge-project
    volumes:
      - ./database:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    secrets:
      - db_root_password
      - db_user_password

  flask:
    container_name: flask
    build: .
    restart: always
    ports:
      - 5000:5000
    networks:
      - bridge-project
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./city.txt
        target: /app/src/city.txt
    depends_on:
      - mariadb

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt